version: 0.2
phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - apt update -y
      - apt install -y python3-pip
      - aws s3 cp s3://$DEPENDENCY_BUCKET/dependencies/env ./.env
      - npm install
      #- npm run coverage
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t service-repo .
      - docker tag service-repo:latest $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - echo Writing image definitions file...
      - printf '[{"name":"%s","imageUri":"%s:latest"}]' $CONTAINER_NAME $REPOSITORY_URI > imagedefinitions.json
artifacts:
  files: imagedefinitions.json
